### ISSUE TITLE
Composer issues and depreciation of uri_for

### ISSUE THREAD

**Issue by Eric-11** [stoufa06/php-garmin-connect-api#12]
I'm new to using composer but I had to add
"vlucas/phpdotenv": "^5.4"

To get the dotenv to work.

I also had to modify:
/vendor/league/oauth1-client/src/Signature/HmacSha1Signature.php
line 37 change to:         return Psr7\Utils::uriFor($uri);

to avoid a fatal error of uri_for being refactored in newer packages.

**Comment by stoufa06** [comment]
@Eric-11 Thank you for your feedback
I will check your issue

**Comment by konstantinosmantzios** [comment]
I also have the same issue
"Call to undefined function GuzzleHttp\Psr7\uri_for()"
