### ISSUE TITLE
getUserDetails returns only a ID

### ISSUE THREAD

**Issue by andymurakami** [stoufa06/php-garmin-connect-api#16]
I´m try to use :

 $userDetails = $server->getUserDetails($tokenCredentials);

Return :

League\OAuth1\Client\Server\User Object
(
    [uid] => ID_RETURNED*
    [nickname] => 
    [name] => 
    [firstName] => 
    [lastName] => 
    [email] => 
    [location] => 
    [description] => 
    [imageUrl] => 
    [urls] => Array
        (
        )

    [extra] => Array
        (
            [userId] => ID_RETURNED*
        )

)

* I´m hide the ID returned.

Any solution ?

**Comment by stoufa06** [comment]
@andymurakami if you read garmin api docs you will see that garmin api gives only the user id, nothing more.

**Comment by andymurakami** [comment]
Sorry I´m think the docs are incomplete.. Thank You.
