### ISSUE TITLE
Backfill php error

### ISSUE THREAD

**Issue by djjavo** [stoufa06/php-garmin-connect-api#4]
I am getting a PHP error `A void function must not return a value` on your `backfill` method. I can see the method has a return statement, is the void annotation correct?

**Comment by stoufa06** [comment]
@djjavo Can you make the changes and open pull request?

**Comment by stoufa06** [comment]
@ajithv11 You need to store $tokenCredentials and userId in your database and retrieve it anytime to request your activity summary

**Comment by stoufa06** [comment]
@djjavo You can use version 1.6 while i fix the errors

**Comment by stoufa06** [comment]
@djjavo I have created new release and fixed the void errors and added example
