### ISSUE TITLE
How to create Authorization header after garmin user authorization for getActivitySummary , backfillActivitySummary  etc 

### ISSUE THREAD

**Issue by ajithv11** [stoufa06/php-garmin-connect-api#6]
I have successfully connected with garmin and getActivitySummary  using $tokenCredentials as given in the README
$tokenCredentials = $server->getTokenCredentials($temporaryCredentials, $_GET['oauth_token'], $_GET['oauth_verifier']); This is possible only while connecting

But is there any way to getActivitySummary later by using connected userId , userIdentifier and Secret ?

**Comment by stoufa06** [comment]
@ajithv11 You need to store $tokenCredentials and userId in your database and retrieve it anytime to request your activity summary

**Comment by ajithv11** [comment]
@stoufa06  Since $tokenCredentials  is an object is it ok to store it as serialize string and later retrieve object through unserialize?

**Comment by stoufa06** [comment]
@ajithv11 yes

**Comment by ajithv11** [comment]
@stoufa06  Could you please share the code.. When I serialize the variable **$tokenCredentials** = 
League\OAuth1\Client\Credentials\TokenCredentials Object
(
[identifier:protected] => ab36a1ac-5132-3a9f-96a0-f4f6e6aa3bfc
[secret:protected] => 4RPbEiQZxDlc10iGBobu3BW4RGfBA5utBs5
)

When I tried to underialize the above object, It gives error  **Notice: unserialize(): Error at offset 79 of 181 bytes**

Any healp would be much appreciated as I am trying this for more than 1 week 

Thanks in Advance :)

**Comment by stoufa06** [comment]
@ajithv11 I have added example folder in the new release.
